---
title: "Probabilitat II"
author: "Santi Perez-Hoyos"
date: '`r format(Sys.time(), "%d %B, %Y")`'
lang: ca
site: bookdown::bookdown_site
---


```{r setup-global, include=FALSE}
knitr::opts_chunk$set(
  fig.path = "images/",
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

<!-- HTML para logos -->



# Pla docent {-}

L’assignatura pretén proporcionar una base sòlida en l’estudi de variables aleatòries multivariants i processos estocàstics, amb èmfasi en la comprensió teòrica, les propietats fonamentals i les aplicacions pràctiques en camps com la ciència de dades, les finances, les biociències i l’enginyeria.


## Dades generals {-}

|                      |                                                    |  
|----------------------|----------------------------------------------------|
|Nom de l'assignatura  | Probabilitat II                                    |
|Codi de l'assignatura |                                                    |
|Curs Acadèmic         | 2026/2027                                          |
|Coordinació           | Santi Pérez Hoyos                                  |
|Departament           |Departament de Genètica, Microbiologia i Estadística|
|Crèdits               |6                                                   |
|Programa Únic         |S                                                   |


## Hores   {-}

|Activitats	                              |  Tipus de formació |Hores  | 
|-----------------------------------------|--------------------|:-----:|
|Activitats presencials i/o no presencials|		                 |  60	 |
|&emsp; - Teoria	                        |    Presencial	     |  30	 |
|&emsp;- Pràctiques de problemes	        |    Presencial      |	30	 |
|Treball tutelat/dirigit	               	|                    |  40	 |
|Aprenentatge autònom		                  |                    |  50	 |


 
## Competències / Resultats d'aprenentatge que es desenvolupen  {-}

**- Competències**

C05. - Aplicar los conocimientos y habilidades a situaciones prácticas

C12. Detectar situacions en què els models estadístics i d’investigació operativa poden ser útils per a la presa de decisions.

C14. Adaptar els models teòrics a les necessitats específiques de les diferents àrees d’aplicació.

**- Habilitats i destreses**

H04. Plantejar una pregunta científica en termes estadístics.

H06. Identificar les fonts de variabilitat i incertesa que afecten la presa de decisions

**- Coneixements i continguts**

K03. Reconèixer la teoria de la probabilitat com a fonament de les tècniques estadístiques.

## Objectius d'aprenentatge  {-}


| Referits a Coneixements                 |  Referits a habilitats, destreses  |
|-----------------------------------------|------------------------------------|
|- Conèixer els conceptes de variables aleatòries multivariants i les seves components |- Calcular probabilitats a partir dels models de vectors aleatoris |
|- Conèixer els conceptes de independència , covariància i correlació  |- Calcular densitats marginals i conjuntes i funcions de vectors aleatoris|
|- Conèixer les principals models multivariants i les seves propietats, i identificar els seus àmbits d'aplicació |- Calcular matrius de covariàncies, correlacions i moments de variables aleatòries multivariants |
|- Conèixer el concepte de procés estocàstic i les seves propietats bàsiques.  |- Calcular probabilitats i generar dades de les principals distribucions|
|- Conèixer  els principals tipus de processos estocàstics i identificar les situacions reals a les quals són aplicables. |- Determinar matrius de transició d'una cadena de Markov amb epai d'estats finits | 
||- Aplicació dels principals tipus de processos estocàstics|

## Blocs Temàtics i Continguts Detallats  {-}

 **1. Variables aleatòries multivariants**
 
 * Definició i conceptes bàsics: vectors aleatoris, espais de probabilitat.
 
 * Funcions de densitat i de distribució conjuntes.
 
 * Funcions de densitat i de distribució marginals i condicionades.
 
 * Moments multivariants: vector d'esperances, matriu de variància-covariància.
 
 * Transformacions de variables multivariants.
 
**2. Independència de variables aleatòries**

* Independència i dependència entre variables aleatòries.

* Esperances i variàncies condicionades.
 
* Conceptes de covariància, correlació i causalitat.
 


**3. Algunes distribucions multivariants**

* Distribució normal multivariant: definició, propietats i aplicacions.
 
* Distribucions especials: Multinomial, t-Student multivariant, Wishart, Chi-quadrat i Dirichlet.
 
* Generació de mostres de distribucions multivariants.

**4. Processos estocàstics: Introducció i conceptes bàsics**

* Definició de procés estocàstic.
 
* Processos estocàstics discrets i continus.
 
* Processos estocàstics estacionaris i no estacionaris.
 
**5. Principals tipus de Processos estocàstics.**

* Cadenes de Markov.

* Caminades aleatòries.

* Processos de Poisson.

* Moviment Brownià.


 
## Metodologia i activitats formatives  {-}

El pla docent es desglossa en els següents tipus metodològics bàsics: activitats presencials, treball dirigit (com ara el lliurament de problemes o l’estudi de casos pràctics de seguiment automatitzat) i treball autònom. Les categories desglossades són:

1. Classes de teoria. Dues sessions setmanals ( durant 15 setmanes) en que es presenten els conceptes més teòrics de l'assigunatura. Es miren amb detalls demostracions, contingut i desenvolupament amb la resolució de situacions o problemes típics amb un enfocamente pràctic

2. Classes pràctiques. Sessions de dues hores setmanals ( durant 15 setmanes) L'alumant disposa al principi de cada tema de una collecció de problemes i exercicis pràctics. A la finalització de cada tema es deixen les solucions en el Campus Virtual.  El professorat comenta les diferents formes d'abordar els problemes i resol en la pissara un classe exercicis tipus. A vegades es deixa temps a la mateixa classe perqué l'alumant pugui resodre algún problema.

Les sessions pràctiques tindràn lloc durant 15 setmanes al semestre en una sessió setmanal de 2 hores. En aquestes sessions el grup es divideix en dos subgrups que rebran la docència al mateix horari per part de dos professors. L’assignació d’alumnes als grups la fa el professorat.

A més, regularment es proposen qüestionaris en el Campus Virtual que cal fer de manera telemàtica i lliurar a través del Campus Virtual la setmana següent. En alguns dels qüestionaris es demana que es lliurin els càlculs i procediments, que cal lliurar a les classes de problemes. Aquests lliuraments, igual que la resta de qüestionaris, s’avaluen.

3. Activitats no presencials dirigides. Amb el suport d’eines informàtiques amb correcció automatitzada (qüestionaris de Moodle que es duen a terme des del Campus Virtual), es fa un seguiment del treball autònom de l’estudiant (40 hores d’activitats dirigides no presencials en total).

4. Treball autònom de l’estudiant per acabar de consolidar tots els conceptes donats (50 hores en total).

Es fa servir el Campus Virtual com a repositori del material del curs i també per concretar les activitats proposades. Alguns dels lliuraments de feines es fan directament en el Campus Virtual.

S’espera que l’alumnat assisteixi a classe sempre, ja que una assistència irregular dificulta l'assoliment de les competències que l’assignatura es marca com a objectius.

## Avaluació acreditativa dels aprenentatges  {-}

**Avaluació continuada**

Es l'opció recomanada per als estudiants que assisteixen regularment i que consta de tres parts.


1.- **Lliurament dels questionaris** proposats en el Campus Virtual (Quest)

2.- **Examen parcial** en acabar el tema 2 que no elimina materia (Parcial)

3.- **Examen final** que coincideix amb la data d'avaluació única segons la data marcada pel Consell Docent. (Final)

Els examens parcial i final tenen  la mateixa estructura, amb una pregunta teórica i entre 2 i 4 problemes. La teoria tindrá un valor entre el 20% el 30%.


La qualificació global de l’assignatura és:

**Global = 0.1 · Màx(Quest, Final) + 0.3 · Màx(Parcial, Final) + 0.6 · Final**

sempre que la nota de l’examen final sigui com a mínim de 4 (sobre 10); en cas contrari la qualificació global de l’assignatura és la nota de l’examen final. Per tant, la nota dels lliuraments i la del parcial es tenen en compte (amb pesos respectius del 10 % i del 30 % de la qualificació global) només si són superiors a la nota de l’examen final.

La nota de la reavaluació no té en compte la nota dels lliuraments setmanals ni la de l’examen parcial; per tant, és simplement la nota de l’examen de reavaluació.

**Avaluació única**

L’alumnat pot optar entre dues formes d’avaluació: avaluació continuada o avaluació única. Qui vulgui renunciar a l’avaluació continuada i acollir-se a l’avaluació única ha de fer-ho abans de la data que s’estableixi, i que es fa pública amb antelació suficient.

La prova d’avaluació única consta de dues parts: teoria (amb un pes entre el 20% i el 30 %) i problemes (amb un pes entre el 70% i el 80 %). Els continguts d’aquesta prova són semblants (en temàtica i dificultat) als explicats a les classes presencials. Aquesta prova avalua les competències de l’assignatura i es fa en la data fixada pel Consell Docent (abans del període de matriculació de l’alumnat).
